version: '3'
services:
  postgres:
    image: postgres
    container_name: grpc-postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - grpc-postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: grpc-redis
    ports:
      - '6380:6379'
    volumes:
      - grpc-redis:/data
volumes:
  grpc-postgres-db:
  grpc-redis:
